Repository wecode-bootcamp-korea/15-1st-Crazytrain-frontend, pull requests merged in 2020-12, with the labels that each got.

#4 폭주하는 오늘의 집 프론트 엔드, 공통 부분 취합했습니다 확인 부탁드립니다!
  package-lock.json
  package.json
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#2 [15기 하태현] feature/common merge 이후 컨플릭트 해결완료
  package-lock.json
  public/data/store/data.json
  public/images/store/gaming_chair.jpg
  src/Pages/Store/Category/Category.js
  src/Pages/Store/Category/Category.scss
  src/Pages/Store/Category/Component/CategoryContent/CategoryContent.js
  src/Pages/Store/Category/Component/CategoryContent/CategoryContent.scss
  src/Pages/Store/Category/Component/CategoryContent/Component/Component/ProductItem/ProductItem.js
  src/Pages/Store/Category/Component/CategoryContent/Component/Component/ProductItem/ProductItem.scss
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentFilter/ContentFilter.js
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentFilter/ContentFilter.scss
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentHeader/Component/ContentHeaderSwiper/ContentHeaderSwiper.js
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentHeader/Component/ContentHeaderSwiper/ContentHeaderSwiper.scss
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentHeader/ContentHeader.js
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentHeader/ContentHeader.scss
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentMdpick/ContentMdpick.js
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentMdpick/ContentMdpick.scss
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentRow/ContentRow.js
  src/Pages/Store/Category/Component/CategoryContent/Component/ContentRow/ContentRow.scss
  src/Pages/Store/Category/Component/CategorySidebar/CategorySidebar.js
  src/Pages/Store/Category/Component/CategorySidebar/CategorySidebar.scss
  src/Pages/Store/Category/Component/CategorySidebar/Component/CategoryDetail/CategoryDetail.js
  src/Pages/Store/Category/Component/CategorySidebar/Component/CategoryDetail/CategoryDetail.scss
  src/Pages/Store/Category/Component/CategorySidebar/Component/CategoryListItem/CategoryListItem.js
  src/Pages/Store/Category/Component/CategorySidebar/Component/CategoryListItem/CategoryListItem.scss
  src/Pages/Store/Store.js
  src/Pages/Store/Store.scss
Labels: Status: 리뷰 진행중

#1 [15기 김성훈] 리뷰 주신대로 리팩토링 완료 하였습니다.
  package-lock.json
  public/data/community/community_card.json
  public/data/community/data.json
  public/images/community/bookmark.svg
  public/images/community/comment.svg
  public/images/community/data.json
  public/images/community/heart.svg
  public/images/community/sampleImage1.jpg
  public/images/community/sampleImage2.jpg
  public/images/community/sampleImage3.jpg
  public/images/community/sampleImage4.jpg
  src/Components/Navigation/Navigation.scss
  src/Pages/Community/Community.js
  src/Pages/Community/CommunityHome/CommunityCardList/CommunityCard.js
  src/Pages/Community/CommunityHome/CommunityCardList/CommunityCard.scss
  src/Pages/Community/CommunityHome/CommunityCardList/CommunityCardList.js
  src/Pages/Community/CommunityHome/CommunityCardList/CommunityCardList.scss
  src/Pages/Community/CommunityHome/CommunityHome.js
  src/Pages/Community/CommunityHome/CommunityHome.scss
  src/Pages/Community/CommunityHome/FilterMenu/FilterSelected.js
  src/Pages/Community/CommunityHome/FilterMenu/FilterSelected.scss
  src/Pages/Community/CommunityHome/FilterMenu/FilterTap.js
  src/Pages/Community/CommunityHome/FilterMenu/FilterTap.scss
  src/Pages/Community/CommunityHome/FilterMenu/FilterTapCard.js
  src/Pages/Community/CommunityHome/FilterMenu/FilterTapCard.scss
  src/Pages/Community/CommunityHome/FilterMenu/FilterTapData.js
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: 리뷰 진행중

#8 [15기 김성훈] 폭주하는 오늘의 집 footer 수정 완료 하였습니다! 리뷰 부탁 드립니다!
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/icon.svg
  src/Pages/Community/CommunityHome/CommunityHome.js
  src/Pages/Community/CommunityHome/CommunityHome.scss
  src/Routes.js
Labels: Status: Accepted

#3 [15기 김영재] Add: 로그인 회원가입 네브바만 분리 완료
  public/data/navigation/data.json
  public/images/login/facebook.png
  public/images/login/kakao.png
  public/images/login/naver.png
  public/images/login/todayhome.png
  public/images/navigation/a.png
  public/images/navigation/bull.png
  public/images/navigation/c.png
  public/images/navigation/cart.png
  public/images/navigation/cheetah.png
  public/images/navigation/d.png
  public/images/navigation/deer.png
  public/images/navigation/drop.png
  public/images/navigation/f.png
  public/images/navigation/footer.png
  public/images/navigation/g.png
  public/images/navigation/glass.png
  public/images/navigation/hippopo.png
  public/images/navigation/lion.png
  public/images/navigation/monkey.png
  public/images/navigation/navToday.png
  public/images/navigation/rhino.png
  public/images/navigation/wild.png
  src/Components/Navigation/CommunityPage.js
  src/Components/Navigation/Navigation.js
  src/Components/Navigation/Navigation.scss
  src/Components/Navigation/StorePage.js
  src/Components/Navigation/WritingList.js
  src/Pages/Account/Login/GuestLogin.js
  src/Pages/Account/Login/Login.js
  src/Pages/Account/Login/login.scss
  src/Pages/Account/Signup/Signup.js
  src/Pages/Account/Signup/Signup.scss
  src/config.js
Labels: Status: Accepted

#6 [15기 김성훈] 폭주하는 오늘의 집, 커뮤니티 상세 페이지, 영재님 브랜치 머지후 난 컴플릭 해결하였습니다!
  public/data/community/community_detail.json
  public/data/community/user_data.json
  public/images/community/community_detail/blog_icon.png
  public/images/community/community_detail/detailSample1.png
  public/images/community/community_detail/detailSample11.png
  public/images/community/community_detail/detailSample2.png
  public/images/community/community_detail/detail_profileSample1.png
  public/images/community/community_detail/detail_profileSample2.png
  public/images/community/community_detail/detail_profileSample3.png
  public/images/community/community_detail/fb_icon.png
  public/images/community/community_detail/google_icon.png
  public/images/community/community_detail/kakao_icon.png
  public/images/community/community_detail/kakaotalk_icon.png
  public/images/community/userprofileimage.jpeg
  src/Components/Navigation/Navigation.scss
  src/Pages/Community/CommunityDetail/CommunityDetail.js
  src/Pages/Community/CommunityDetail/CommunityDetail.scss
  src/Pages/Community/CommunityDetail/CommunityDetailAside/CommunityDetailAside.js
  src/Pages/Community/CommunityDetail/CommunityDetailAside/CommunityDetailAside.scss
  src/Pages/Community/CommunityDetail/CommunityDetailAside/bookmark_icon.svg
  src/Pages/Community/CommunityDetail/CommunityDetailAside/heart_icon.svg
  src/Pages/Community/CommunityDetail/CommunityDetailMain/CommunityDetailMain.js
  src/Pages/Community/CommunityDetail/CommunityDetailMain/CommunityDetailMain.scss
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/Comment.js
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/Comment.scss
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/DetailBody.js
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/DetailBody.scss
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/Marker.js
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/Marker.scss
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/SubImage.js
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/SubImage.scss
  src/Pages/Community/CommunityDetail/CommunityDetailMain/Components/marker_icon.svg
  src/Pages/Community/CommunityHome/CommunityCardList/CommunityCard.js
  src/Pages/Community/CommunityHome/CommunityHome.js
  src/Pages/Community/CommunityHome/FilterMenu/FilterTap.js
  src/Pages/Store/Product/Product.js
  src/Pages/Store/Store.js
  src/Routes.js
  src/Styles/common.scss
Labels: Status: Accepted

#11 [15기 하태현] 상품 상세페이지 레이아웃 완료 후 백엔드 API 대기중
  public/data/store/data.json
  public/data/store/products2.json
  public/data/store/products3.json
  src/Pages/Store/Category/Category.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/CategoryContent.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentFilter/ContentFilter.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentFilter/FilterControl/FilterControl.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentFilter/FilterList/FilterList.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentFilter/FilterList/FilterList.scss
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentFilter/FilterTag/FilterTag.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentFilter/FilterTag/FilterTag.scss
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentHeader/ContentHeader.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentMdpick/ContentMdpick.js
  src/Pages/Store/Category/CategoryHome/CategoryContent/ContentRow/ContentRow.js
  src/Pages/Store/Category/CategoryHome/CategorySidebar/CategoryDetail/CategoryDetail.js
  src/Pages/Store/Category/CategoryHome/CategorySidebar/CategoryDetail/CategoryDetail.scss
  src/Pages/Store/Category/CategoryHome/CategorySidebar/CategorySidebar.js
  src/Pages/Store/Component/SalesArticle/SalesArticle.js
  src/Pages/Store/Product/Product.js
  src/Pages/Store/Product/Product.scss
  src/Pages/Store/Store.js
  src/Pages/Store/test.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청
